2023-03-21 09:45:23,123 p=437 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 09:45:23,123 p=437 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 09:45:23,234 p=437 u=thibgrev n=ansible | ERROR! Empty playbook, nothing to do
2023-03-21 09:45:29,073 p=448 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 09:45:29,073 p=448 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 09:45:29,085 p=448 u=thibgrev n=ansible | {
    "_meta": {
        "hostvars": {
            "srvad1.BSCLAB.LOCAL": {
                "ansible_connection": "winrm",
                "ansible_password": "azerty@12345",
                "ansible_user": "administrator@bsclab.local",
                "ansible_winrm_port": 5985
            }
        }
    },
    "all": {
        "children": [
            "red_hat",
            "ungrouped",
            "windows"
        ]
    },
    "red_hat": {
        "hosts": [
            "bastion.BSCLAB.LOCAL",
            "vm-redhat-aap.BSCLAB.LOCAL",
            "vm-redhat-ansible.BSCLAB.LOCAL",
            "vm-redhat-setup.BASCAL.LOCAL"
        ]
    },
    "ungrouped": {
        "hosts": [
            "datacenter:children]",
            "red_hat",
            "windows"
        ]
    },
    "windows": {
        "hosts": [
            "srvad1.BSCLAB.LOCAL"
        ]
    }
}
2023-03-21 10:07:54,111 p=688 u=thibgrev n=ansible | ERROR! the playbook: Playbook/tg.yml could not be found
2023-03-21 10:08:04,670 p=738 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 10:08:04,670 p=738 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 10:08:04,798 p=738 u=thibgrev n=ansible | playbook: Playbook/tg.yml
2023-03-21 10:17:18,762 p=4633 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 10:17:18,762 p=4633 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 10:17:18,868 p=4633 u=thibgrev n=ansible | playbook: Playbook/tg.yml
2023-03-21 11:47:45,781 p=11397 u=thibgrev n=ansible | ERROR! the playbook: Playbook/test.yml could not be found
2023-03-21 11:47:45,819 p=11413 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 11:47:45,819 p=11413 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 11:47:45,869 p=11429 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 11:47:45,869 p=11429 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 11:47:45,969 p=11429 u=thibgrev n=ansible | ERROR! Empty playbook, nothing to do
2023-03-21 11:47:45,975 p=11413 u=thibgrev n=ansible | playbook: Playbook/tg.yml
2023-03-21 11:47:46,001 p=11445 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 11:47:46,002 p=11445 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 11:47:46,096 p=11445 u=thibgrev n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected key

The error appears to be in '/home/thibgrev/Ansible/Playbook/test-lint.yml': line 14, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


      - name: test
      ^ here

2023-03-21 10:47:49,659 p=10 u=root n=ansible | {"/usr/share/ansible/collections/ansible_collections": {"kubernetes.core": {"version": "2.3.2"}, "redhatinsights.insights": {"version": "1.0.7"}, "containers.podman": {"version": "1.9.4"}, "ansible.posix": {"version": "1.4.0"}, "ansible.windows": {"version": "1.11.1"}, "theforeman.foreman": {"version": "3.6.0"}, "awx.awx": {"version": "21.7.0"}}}
2023-03-21 10:47:50,373 p=17 u=root n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 10:47:50,373 p=17 u=root n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 10:47:50,531 p=17 u=root n=ansible | PLAY [test] ********************************************************************
2023-03-21 10:47:50,542 p=17 u=root n=ansible | TASK [Gathering Facts] *********************************************************
2023-03-21 10:47:50,580 p=17 u=root n=ansible | fatal: [datacenter:children]]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname datacenter:children]: Name or service not known", "unreachable": true}
2023-03-21 10:47:50,760 p=17 u=root n=ansible | fatal: [vm-redhat-aap.BSCLAB.LOCAL]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname vm-redhat-aap.bsclab.local: Name or service not known", "unreachable": true}
2023-03-21 10:47:50,800 p=17 u=root n=ansible | fatal: [vm-redhat-ansible.BSCLAB.LOCAL]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname vm-redhat-ansible.bsclab.local: Name or service not known", "unreachable": true}
2023-03-21 10:47:50,805 p=17 u=root n=ansible | fatal: [srvad1.BSCLAB.LOCAL]: FAILED! => {"msg": "The field 'password' has an invalid value, which includes an undefined variable. The error was: 'vault_ansible_user_for_windows_password' is undefined. 'vault_ansible_user_for_windows_password' is undefined"}
2023-03-21 10:47:50,805 p=17 u=root n=ansible | fatal: [vm-redhat-setup.BASCAL.LOCAL]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname vm-redhat-setup.bascal.local: Name or service not known", "unreachable": true}
2023-03-21 10:47:50,930 p=17 u=root n=ansible | fatal: [bastion.BSCLAB.LOCAL]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname bastion.bsclab.local: Name or service not known", "unreachable": true}
2023-03-21 10:48:00,582 p=17 u=root n=ansible | fatal: [red_hat]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname red_hat: Name or service not known", "unreachable": true}
2023-03-21 10:48:00,585 p=17 u=root n=ansible | fatal: [windows]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname windows: Name or service not known", "unreachable": true}
2023-03-21 10:48:00,586 p=17 u=root n=ansible | PLAY RECAP *********************************************************************
2023-03-21 10:48:00,586 p=17 u=root n=ansible | bastion.BSCLAB.LOCAL       : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2023-03-21 10:48:00,586 p=17 u=root n=ansible | datacenter:children]       : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2023-03-21 10:48:00,586 p=17 u=root n=ansible | red_hat                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2023-03-21 10:48:00,587 p=17 u=root n=ansible | srvad1.BSCLAB.LOCAL        : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2023-03-21 10:48:00,587 p=17 u=root n=ansible | vm-redhat-aap.BSCLAB.LOCAL : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2023-03-21 10:48:00,587 p=17 u=root n=ansible | vm-redhat-ansible.BSCLAB.LOCAL : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2023-03-21 10:48:00,587 p=17 u=root n=ansible | vm-redhat-setup.BASCAL.LOCAL : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2023-03-21 10:48:00,587 p=17 u=root n=ansible | windows                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2023-03-21 11:48:51,562 p=11799 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 11:48:51,562 p=11799 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 11:48:51,576 p=11799 u=thibgrev n=ansible | {
    "_meta": {
        "hostvars": {
            "srvad1.BSCLAB.LOCAL": {
                "ansible_connection": "winrm",
                "ansible_password": "azerty@12345",
                "ansible_user": "administrator@bsclab.local",
                "ansible_winrm_port": 5985
            }
        }
    },
    "all": {
        "children": [
            "red_hat",
            "ungrouped",
            "windows"
        ]
    },
    "red_hat": {
        "hosts": [
            "bastion.BSCLAB.LOCAL",
            "vm-redhat-aap.BSCLAB.LOCAL",
            "vm-redhat-ansible.BSCLAB.LOCAL",
            "vm-redhat-setup.BASCAL.LOCAL"
        ]
    },
    "ungrouped": {
        "hosts": [
            "datacenter:children]",
            "red_hat",
            "windows"
        ]
    },
    "windows": {
        "hosts": [
            "srvad1.BSCLAB.LOCAL"
        ]
    }
}
2023-03-21 11:48:54,478 p=11824 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 11:48:54,478 p=11824 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 11:48:54,607 p=11824 u=thibgrev n=ansible | playbook: Playbook/tg.yml
2023-03-21 10:48:59,050 p=10 u=root n=ansible | {"/usr/share/ansible/collections/ansible_collections": {"kubernetes.core": {"version": "2.3.2"}, "redhatinsights.insights": {"version": "1.0.7"}, "containers.podman": {"version": "1.9.4"}, "ansible.posix": {"version": "1.4.0"}, "ansible.windows": {"version": "1.11.1"}, "theforeman.foreman": {"version": "3.6.0"}, "awx.awx": {"version": "21.7.0"}}}
2023-03-21 10:48:59,737 p=17 u=root n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 10:48:59,737 p=17 u=root n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 10:48:59,937 p=17 u=root n=ansible | PLAY [test] ********************************************************************
2023-03-21 10:48:59,948 p=17 u=root n=ansible | TASK [Gathering Facts] *********************************************************
2023-03-21 10:49:00,889 p=17 u=root n=ansible | ok: [localhost]
2023-03-21 10:49:00,904 p=17 u=root n=ansible | TASK [install NGinx packages on RHEL] ******************************************
2023-03-21 10:49:00,916 p=17 u=root n=ansible | ok: [localhost] => {
    "msg": "yessssssssssssssssss"
}
2023-03-21 10:49:00,931 p=17 u=root n=ansible | PLAY RECAP *********************************************************************
2023-03-21 10:49:00,931 p=17 u=root n=ansible | localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2023-03-21 11:50:38,579 p=12360 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 11:50:38,579 p=12360 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 11:50:38,676 p=12379 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 11:50:38,677 p=12379 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 11:50:38,680 p=12360 u=thibgrev n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected key

The error appears to be in '/home/thibgrev/Ansible/Playbook/test-lint.yml': line 14, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


      - name: test
      ^ here

2023-03-21 11:50:38,697 p=12395 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 11:50:38,698 p=12395 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 11:50:38,772 p=12379 u=thibgrev n=ansible | ERROR! no module/action detected in task.

The error appears to be in '/home/thibgrev/Ansible/Playbook/test-wisdom.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: "Install NGinx server and start"
      ^ here

2023-03-21 11:50:38,804 p=12395 u=thibgrev n=ansible | playbook: Playbook/test.yml
2023-03-21 12:02:11,888 p=12614 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 12:02:11,889 p=12614 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 12:02:12,005 p=12614 u=thibgrev n=ansible | ERROR! no module/action detected in task.

The error appears to be in '/home/thibgrev/Ansible/Playbook/test-wisdom.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: "Install NGinx server and start"
      ^ here

2023-03-21 12:02:25,603 p=12670 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 12:02:25,603 p=12670 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 12:02:25,708 p=12670 u=thibgrev n=ansible | PLAY [test] ***********************************************************************************************************************************************************
2023-03-21 12:02:25,721 p=12670 u=thibgrev n=ansible | TASK [Gathering Facts] ************************************************************************************************************************************************
2023-03-21 12:02:26,084 p=12670 u=thibgrev n=ansible | fatal: [localhost]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"ansible.legacy.setup": {"failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: ansible.legacy.setup\n"}
2023-03-21 12:02:26,085 p=12670 u=thibgrev n=ansible | PLAY RECAP ************************************************************************************************************************************************************
2023-03-21 12:02:26,085 p=12670 u=thibgrev n=ansible | localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2023-03-21 12:02:39,509 p=12751 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 12:02:39,510 p=12751 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 12:02:39,639 p=12751 u=thibgrev n=ansible | playbook: Playbook/tg.yml
2023-03-21 12:02:41,044 p=12770 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 12:02:41,044 p=12770 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 12:02:41,134 p=12770 u=thibgrev n=ansible | PLAY [test] ***********************************************************************************************************************************************************
2023-03-21 12:02:41,144 p=12770 u=thibgrev n=ansible | TASK [install NGinx packages on RHEL] *********************************************************************************************************************************
2023-03-21 12:02:41,152 p=12770 u=thibgrev n=ansible | ok: [localhost] => {
    "msg": "yessssssssssssssssss"
}
2023-03-21 12:02:41,156 p=12770 u=thibgrev n=ansible | PLAY RECAP ************************************************************************************************************************************************************
2023-03-21 12:02:41,156 p=12770 u=thibgrev n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2023-03-21 11:02:46,625 p=10 u=root n=ansible | {"/usr/share/ansible/collections/ansible_collections": {"kubernetes.core": {"version": "2.3.2"}, "redhatinsights.insights": {"version": "1.0.7"}, "containers.podman": {"version": "1.9.4"}, "ansible.posix": {"version": "1.4.0"}, "ansible.windows": {"version": "1.11.1"}, "theforeman.foreman": {"version": "3.6.0"}, "awx.awx": {"version": "21.7.0"}}}
2023-03-21 11:02:47,345 p=17 u=root n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 11:02:47,345 p=17 u=root n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 11:02:47,491 p=17 u=root n=ansible | PLAY [test] ********************************************************************
2023-03-21 11:02:47,506 p=17 u=root n=ansible | TASK [install NGinx packages on RHEL] ******************************************
2023-03-21 11:02:47,531 p=17 u=root n=ansible | ok: [localhost] => {
    "msg": "yessssssssssssssssss"
}
2023-03-21 11:02:47,542 p=17 u=root n=ansible | PLAY RECAP *********************************************************************
2023-03-21 11:02:47,542 p=17 u=root n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2023-03-21 12:04:12,571 p=13036 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-21 12:04:12,571 p=13036 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-21 12:04:12,706 p=13036 u=thibgrev n=ansible | playbook: Playbook/tg.yml
2023-03-23 15:07:53,140 p=6189 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-23 15:07:53,140 p=6189 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-23 15:07:53,263 p=6189 u=thibgrev n=ansible | ERROR! A playbook must be a list of plays, got a <class 'ansible.parsing.yaml.objects.AnsibleMapping'> instead

The error appears to be in '/home/thibgrev/Ansible/ansible-navigator.yml': line 1, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


ansible-navigator:
^ here

2023-03-23 15:07:57,631 p=6231 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-23 15:07:57,631 p=6231 u=thibgrev n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-23 15:07:57,777 p=6231 u=thibgrev n=ansible | playbook: Playbook/test.yml
2023-03-23 14:08:01,164 p=10 u=root n=ansible | {"/usr/share/ansible/collections/ansible_collections": {"redhatinsights.insights": {"version": "1.0.7"}, "containers.podman": {"version": "1.9.4"}, "awx.awx": {"version": "21.7.0"}, "ansible.windows": {"version": "1.11.1"}, "ansible.posix": {"version": "1.4.0"}, "theforeman.foreman": {"version": "3.6.0"}, "kubernetes.core": {"version": "2.3.2"}}}
2023-03-23 14:08:02,753 p=17 u=root n=ansible | [WARNING]: Found both group and host with same name: red_hat

2023-03-23 14:08:02,753 p=17 u=root n=ansible | [WARNING]: Found both group and host with same name: windows

2023-03-23 14:08:03,254 p=17 u=root n=ansible | PLAY [test] ********************************************************************
2023-03-23 14:08:03,286 p=17 u=root n=ansible | TASK [Gathering Facts] *********************************************************
2023-03-23 14:08:05,063 p=17 u=root n=ansible | ok: [localhost]
2023-03-23 14:08:05,098 p=17 u=root n=ansible | TASK [debug module] ************************************************************
2023-03-23 14:08:05,124 p=17 u=root n=ansible | ok: [localhost] => {
    "msg": "test"
}
2023-03-23 14:08:05,162 p=17 u=root n=ansible | PLAY RECAP *********************************************************************
2023-03-23 14:08:05,162 p=17 u=root n=ansible | localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
